In [27]:
import pandas as pd
from pathlib import Path
from warnings import filterwarnings

filterwarnings("ignore")

In [28]:
PASTA_ATUAL = Path.cwd()

CAMINHO = (Path.cwd().parent/ "data"/ "raw"/ "Preços semestrais - AUTOMOTIVOS_2026.01.csv")

data_anp = pd.read_csv(
    CAMINHO,
    sep=";",
    decimal=",",
    encoding="utf-8-sig",  
    dtype={"CNPJ da Revenda": "string", "Cep": "string", "Numero Rua": "string"},
)

data_anp["Data da Coleta"] = pd.to_datetime(data_anp["Data da Coleta"], format="%d/%m/%Y")

In [29]:
data_anp.head()

,Regiao - Sigla,Estado - Sigla,Municipio,Revenda,CNPJ da Revenda,Nome da Rua,Numero Rua,Complemento,Bairro,Cep,Produto,Data da Coleta,Valor de Venda,Valor de Compra,Unidade de Medida,Bandeira
0,N,AC,CRUZEIRO DO SUL,AMAZONIA COMERCIO DE DERIVADOS DE PETROLEO LTDA,01.492.748/0003-83,AVENIDA COPACABANA,440,NaN,COPACABANA,69980-000,GASOLINA,2026-01-02,7.97,NaN,R$ / litro,IPIRANGA
1,N,AC,CRUZEIRO DO SUL,AMAZONIA COMERCIO DE DERIVADOS DE PETROLEO LTDA,01.492.748/0003-83,AVENIDA COPACABANA,440,NaN,COPACABANA,69980-000,DIESEL,2026-01-02,8.15,NaN,R$ / litro,IPIRANGA
2,N,AC,CRUZEIRO DO SUL,AMAZONIA COMERCIO DE DERIVADOS DE PETROLEO LTDA,01.492.748/0003-83,AVENIDA COPACABANA,440,NaN,COPACABANA,69980-000,DIESEL S10,2026-01-02,8.17,NaN,R$ / litro,IPIRANGA
3,N,AC,RIO BRANCO,AUTO POSTO AMAPA LTDA,00.529.581/0001-53,VIA CHICO MENDES,3570,NaN,AREAL,69906-119,GASOLINA,2026-01-02,7.29,NaN,R$ / litro,VIBRA
4,N,AC,RIO BRANCO,AUTO POSTO AMAPA LTDA,00.529.581/0001-53,VIA CHICO MENDES,3570,NaN,AREAL,69906-119,GASOLINA ADITIVADA,2026-01-02,7.39,NaN,R$ / litro,VIBRA

In [30]:
data_anp["Data da Coleta"].dt.strftime("%d/%m/%Y").agg(["min", "max"])

min    01/01/2026
max    31/03/2026
Name: Data da Coleta, dtype: str

In [31]:
data_anp.shape

(422418, 16)

In [32]:
data_anp.info()

<class 'pandas.DataFrame'>
RangeIndex: 422418 entries, 0 to 422417
Data columns (total 16 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   Regiao - Sigla     422418 non-null  str
 1   Estado - Sigla     422418 non-null  str
 2   Municipio          422418 non-null  str
 3   Revenda            422418 non-null  str
 4   CNPJ da Revenda    422418 non-null  string
 5   Nome da Rua        422418 non-null  str
 6   Numero Rua         422412 non-null  string
 7   Complemento        96159 non-null   str
 8   Bairro             421690 non-null  str
 9   Cep                422418 non-null  string
 10  Produto            422418 non-null  str
 11  Data da Coleta     422418 non-null  datetime64[us]
 12  Valor de Venda     422418 non-null  float64
 13  Valor de Compra    0 non-null       float64
 14  Unidade de Medida  422418 non-null  str
 15  Bandeira           422418 non-null  str
dtypes: datetime64[us](1), float64(2), str(10), string(3)
memory usage: 108.0 MB

In [33]:
data_anp.isna().sum()

Regiao - Sigla            0
Estado - Sigla            0
Municipio                 0
Revenda                   0
CNPJ da Revenda           0
Nome da Rua               0
Numero Rua                6
Complemento          326259
Bairro                  728
Cep                       0
Produto                   0
Data da Coleta            0
Valor de Venda            0
Valor de Compra      422418
Unidade de Medida         0
Bandeira                  0
dtype: int64

In [34]:
data_anp['Valor de Compra'] = data_anp['Valor de Compra'].fillna('NAO INFORMADO')
print(data_anp.isna().sum())

Regiao - Sigla            0
Estado - Sigla            0
Municipio                 0
Revenda                   0
CNPJ da Revenda           0
Nome da Rua               0
Numero Rua                6
Complemento          326259
Bairro                  728
Cep                       0
Produto                   0
Data da Coleta            0
Valor de Venda            0
Valor de Compra           0
Unidade de Medida         0
Bandeira                  0
dtype: int64

In [35]:
data_anp_tratado = data_anp.copy()

In [36]:
data_anp_tratado.drop(columns=["Nome da Rua", "Numero Rua", "Complemento", "Bairro", "Valor de Compra", "Regiao - Sigla"], inplace=True)

In [37]:
data_anp_tratado.rename(columns={"Estado - Sigla": "Estado"}, inplace=True)
data_anp_tratado.head()

,Estado,Municipio,Revenda,CNPJ da Revenda,Cep,Produto,Data da Coleta,Valor de Venda,Unidade de Medida,Bandeira
0,AC,CRUZEIRO DO SUL,AMAZONIA COMERCIO DE DERIVADOS DE PETROLEO LTDA,01.492.748/0003-83,69980-000,GASOLINA,2026-01-02,7.97,R$ / litro,IPIRANGA
1,AC,CRUZEIRO DO SUL,AMAZONIA COMERCIO DE DERIVADOS DE PETROLEO LTDA,01.492.748/0003-83,69980-000,DIESEL,2026-01-02,8.15,R$ / litro,IPIRANGA
2,AC,CRUZEIRO DO SUL,AMAZONIA COMERCIO DE DERIVADOS DE PETROLEO LTDA,01.492.748/0003-83,69980-000,DIESEL S10,2026-01-02,8.17,R$ / litro,IPIRANGA
3,AC,RIO BRANCO,AUTO POSTO AMAPA LTDA,00.529.581/0001-53,69906-119,GASOLINA,2026-01-02,7.29,R$ / litro,VIBRA
4,AC,RIO BRANCO,AUTO POSTO AMAPA LTDA,00.529.581/0001-53,69906-119,GASOLINA ADITIVADA,2026-01-02,7.39,R$ / litro,VIBRA

In [38]:
ordem = data_anp_tratado.columns.tolist()

ordem.remove("Unidade de Medida")
ordem.insert(ordem.index("Valor de Venda"), "Unidade de Medida")

ordem.remove("Produto")
ordem.insert(ordem.index("Data da Coleta") + 1, "Produto")

data_anp_tratado = data_anp_tratado[ordem]

In [39]:
data_anp_tratado.head()

,Estado,Municipio,Revenda,CNPJ da Revenda,Cep,Data da Coleta,Produto,Unidade de Medida,Valor de Venda,Bandeira
0,AC,CRUZEIRO DO SUL,AMAZONIA COMERCIO DE DERIVADOS DE PETROLEO LTDA,01.492.748/0003-83,69980-000,2026-01-02,GASOLINA,R$ / litro,7.97,IPIRANGA
1,AC,CRUZEIRO DO SUL,AMAZONIA COMERCIO DE DERIVADOS DE PETROLEO LTDA,01.492.748/0003-83,69980-000,2026-01-02,DIESEL,R$ / litro,8.15,IPIRANGA
2,AC,CRUZEIRO DO SUL,AMAZONIA COMERCIO DE DERIVADOS DE PETROLEO LTDA,01.492.748/0003-83,69980-000,2026-01-02,DIESEL S10,R$ / litro,8.17,IPIRANGA
3,AC,RIO BRANCO,AUTO POSTO AMAPA LTDA,00.529.581/0001-53,69906-119,2026-01-02,GASOLINA,R$ / litro,7.29,VIBRA
4,AC,RIO BRANCO,AUTO POSTO AMAPA LTDA,00.529.581/0001-53,69906-119,2026-01-02,GASOLINA ADITIVADA,R$ / litro,7.39,VIBRA

In [40]:
data_es = data_anp_tratado[data_anp_tratado["Estado"] == "ES"].copy()
data_es.head()

,Estado,Municipio,Revenda,CNPJ da Revenda,Cep,Data da Coleta,Produto,Unidade de Medida,Valor de Venda,Bandeira
16,ES,LINHARES,AUTO SERVICO FLORESTA LTDA,05.609.081/0001-45,29900-100,2026-01-02,GASOLINA,R$ / litro,6.59,VIBRA
17,ES,LINHARES,AUTO SERVICO FLORESTA LTDA,05.609.081/0001-45,29900-100,2026-01-02,DIESEL,R$ / litro,5.89,VIBRA
18,ES,LINHARES,CAMATTA & CIA LTDA,30.578.975/0001-62,29901-260,2026-01-02,GASOLINA,R$ / litro,6.59,IPIRANGA
19,ES,LINHARES,CAMATTA & CIA LTDA,30.578.975/0001-62,29901-260,2026-01-02,GASOLINA ADITIVADA,R$ / litro,6.59,IPIRANGA
20,ES,LINHARES,CAMATTA & CIA LTDA,30.578.975/0001-62,29901-260,2026-01-02,DIESEL,R$ / litro,5.89,IPIRANGA

In [41]:
data_es.rename(columns={"Valor de Venda": "Valor", "CNPJ da Revenda": "CNPJ", "Data da Coleta": "Data_Coleta", "Unidade de Medida": "Uni_Medida"}, inplace=True)

In [46]:
data_es.head()

,Estado,Municipio,Revenda,CNPJ,Cep,Data_Coleta,Produto,Uni_Medida,Valor,Bandeira
16,ES,LINHARES,AUTO SERVICO FLORESTA LTDA,05.609.081/0001-45,29900-100,2026-01-02,GASOLINA,R$ / litro,6.59,VIBRA
17,ES,LINHARES,AUTO SERVICO FLORESTA LTDA,05.609.081/0001-45,29900-100,2026-01-02,DIESEL,R$ / litro,5.89,VIBRA
18,ES,LINHARES,CAMATTA & CIA LTDA,30.578.975/0001-62,29901-260,2026-01-02,GASOLINA,R$ / litro,6.59,IPIRANGA
19,ES,LINHARES,CAMATTA & CIA LTDA,30.578.975/0001-62,29901-260,2026-01-02,GASOLINA ADITIVADA,R$ / litro,6.59,IPIRANGA
20,ES,LINHARES,CAMATTA & CIA LTDA,30.578.975/0001-62,29901-260,2026-01-02,DIESEL,R$ / litro,5.89,IPIRANGA

In [42]:
data_es.to_csv(
    PASTA_ATUAL.parent / "data" / "raw" / "data_es.csv",
    sep=";",    index=False
)

### Perguntas SQL

In [2]:
from pathlib import Path
import duckdb

raiz = Path.cwd().parent  # a pasta do projeto, partindo de notebooks/
consulta_01 = (raiz / "sql" / "01_perfil.sql").read_text(encoding="utf-8")
consulta_02 = (raiz / "sql" / "02_perfil.sql").read_text(encoding="utf-8")
consulta_03 = (raiz / "sql" / "03-perfil.sql").read_text(encoding="utf-8")

In [49]:
duckdb.sql(consulta_01).df()

               Produto                Municipio  total_linhas
0             GASOLINA               VILA VELHA           413
1   GASOLINA ADITIVADA               VILA VELHA           383
2             GASOLINA                    SERRA           363
3   GASOLINA ADITIVADA                    SERRA           333
4             GASOLINA                  VITORIA           311
5   GASOLINA ADITIVADA                  VITORIA           311
6               ETANOL                    SERRA           303
7             GASOLINA                CARIACICA           302
8           DIESEL S10               VILA VELHA           300
9               ETANOL               VILA VELHA           280
10              ETANOL                CARIACICA           271
11              ETANOL                  VITORIA           249
12  GASOLINA ADITIVADA                CARIACICA           241
13          DIESEL S10                    SERRA           229
14            GASOLINA                GUARAPARI           207
15  GASOLINA ADITIVADA                GUARAPARI           204
16          DIESEL S10                CARIACICA           195
17            GASOLINA                 COLATINA           192
18              DIESEL                    SERRA           150
19  GASOLINA ADITIVADA                 COLATINA           148
20            GASOLINA                 LINHARES           143
21              DIESEL                 COLATINA           117
22            GASOLINA               SAO MATEUS           116
23              DIESEL                CARIACICA           112
24              ETANOL                GUARAPARI           106
25              DIESEL               VILA VELHA           101
26          DIESEL S10                  VITORIA           101
27            GASOLINA  CACHOEIRO DE ITAPEMIRIM            99
28          DIESEL S10                 COLATINA            98
29  GASOLINA ADITIVADA                 LINHARES            95
30                 GNV                CARIACICA            95
31          DIESEL S10               SAO MATEUS            94
32          DIESEL S10                GUARAPARI            91
33          DIESEL S10  CACHOEIRO DE ITAPEMIRIM            81
34              ETANOL  CACHOEIRO DE ITAPEMIRIM            80
35              DIESEL                 LINHARES            78
36              ETANOL               SAO MATEUS            78
37              DIESEL  CACHOEIRO DE ITAPEMIRIM            77
38  GASOLINA ADITIVADA  CACHOEIRO DE ITAPEMIRIM            72
39              ETANOL                 COLATINA            70
40          DIESEL S10                 LINHARES            49
41  GASOLINA ADITIVADA               SAO MATEUS            43
42              ETANOL                 LINHARES            39
43                 GNV                    SERRA            30
44                 GNV                  VITORIA            30
45              DIESEL               SAO MATEUS            29
46              DIESEL                  ARACRUZ            28
47          DIESEL S10                  ARACRUZ            28
48            GASOLINA                  ARACRUZ            28
49  GASOLINA ADITIVADA                  ARACRUZ            28
50                 GNV               VILA VELHA            28
51              DIESEL                GUARAPARI            24
52                 GNV  CACHOEIRO DE ITAPEMIRIM            13
53                 GNV               SAO MATEUS            13
54                 GNV                 COLATINA            10
55              ETANOL                  ARACRUZ             6
56                 GNV                 LINHARES             2

In [54]:
duckdb.sql(consulta_02).df()

              Produto  preco_medio  preco_mediano  preco_minimo  preco_maximo
0              DIESEL         6.51           6.69          5.79          7.69
1          DIESEL S10         6.61           6.79          5.79          7.89
2              ETANOL         4.90           4.89          4.35          5.99
3            GASOLINA         6.50           6.49          5.87          7.45
4  GASOLINA ADITIVADA         6.68           6.69          5.89          7.99
5                 GNV         4.17           4.09          3.98          4.98

In [3]:
duckdb.sql(consulta_03).df()

IOException: IO Error: No files found that match the pattern "data/raw/data_es.csv"

LINE 7: FROM read_csv(
             ^