In [1]:
import pandas as pd
import numpy as np
import plotly.express as px
import warnings
warnings.filterwarnings("ignore")

In [4]:
caminho = r'C:\Projetos\ES-fuel-intelligence\data\raw\revendas_lpc_2026_10_18-2026_10_24.xlsx'

excel = pd.ExcelFile(caminho)
print(excel.sheet_names)

['POSTOS REVENDEDORES']

In [ ]:
data = pd.read_excel(
    "C:/Projetos/ES-fuel-intelligence/data/raw/revendas_lpc_2026_10_18-2026_10_24.xlsx",
    sheet_name="POSTOS REVENDEDORES",
    header=9
)

data.head()

In [9]:
data.to_csv(
    "../data/processed/revendas_2026_10_18-2026_10_24.csv",
    index=False,
    encoding="utf-8-sig"
)

In [14]:
data_semana = pd.read_csv(
    "../data/processed/preco_medio_semanal_outubro.csv",
    encoding="utf-8-sig")

In [19]:
data_semana.head(2)

,CNPJ,RAZÃO,FANTASIA,ENDEREÇO,NÚMERO,COMPLEMENTO,BAIRRO,CEP,MUNICÍPIO,ESTADO,BANDEIRA,PRODUTO,UNIDADE DE MEDIDA,PREÇO DE REVENDA,DATA DA COLETA
0,61602199002409,COMPANHIA ULTRAGAZ S A,ULTRAGAZ,RUA AMARO CASTRO LIMA,1852,NaN,VILA NOVA CAMPO GRANDE,79106361,CAMPO GRANDE,MATO GROSSO DO SUL,ULTRAGAZ,GLP,R$ / 13 kg,100.0,2026-10-19
1,19791896007024,SUPERGASBRAS ENERGIA LTDA,SUPERGASBRAS ENERGIA,AVENIDA DEP. PLINIO RIBEIRO,3220,NaN,JARDIM PALMEIRAS,39402194,MONTES CLAROS,MINAS GERAIS,SUPERGASBRAS ENERGIA,GLP,R$ / 13 kg,120.0,2026-10-22

In [15]:
data_semana.info()

<class 'pandas.DataFrame'>
RangeIndex: 20926 entries, 0 to 20925
Data columns (total 15 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   CNPJ               20926 non-null  int64
 1   RAZÃO              20926 non-null  str
 2   FANTASIA           8177 non-null   str
 3   ENDEREÇO           20926 non-null  str
 4   NÚMERO             20926 non-null  str
 5   COMPLEMENTO        4971 non-null   str
 6   BAIRRO             20894 non-null  str
 7   CEP                20926 non-null  int64
 8   MUNICÍPIO          20926 non-null  str
 9   ESTADO             20926 non-null  str
 10  BANDEIRA           20926 non-null  str
 11  PRODUTO            20926 non-null  str
 12  UNIDADE DE MEDIDA  20926 non-null  str
 13  PREÇO DE REVENDA   20926 non-null  float64
 14  DATA DA COLETA     20926 non-null  str
dtypes: float64(1), int64(2), str(12)
memory usage: 5.1 MB

In [28]:
data_semana[data_semana["ESTADO"] == "ESPIRITO SANTO"]

,CNPJ,RAZÃO,FANTASIA,ENDEREÇO,NÚMERO,COMPLEMENTO,BAIRRO,CEP,MUNICÍPIO,ESTADO,BANDEIRA,PRODUTO,UNIDADE DE MEDIDA,PREÇO DE REVENDA,DATA DA COLETA
512,36411940000200,VESCOVI & BITTI LTDA,POSTO TREVAO,AVENIDA FLORESTAL,838,NaN,SEGATTO,29192154,ARACRUZ,ESPIRITO SANTO,VIBRA,GASOLINA COMUM,R$ / litro,6.64,2026-10-23
513,36411940000200,VESCOVI & BITTI LTDA,POSTO TREVAO,AVENIDA FLORESTAL,838,NaN,SEGATTO,29192154,ARACRUZ,ESPIRITO SANTO,VIBRA,GASOLINA ADITIVADA,R$ / litro,6.94,2026-10-23
514,36411940000200,VESCOVI & BITTI LTDA,POSTO TREVAO,AVENIDA FLORESTAL,838,NaN,SEGATTO,29192154,ARACRUZ,ESPIRITO SANTO,VIBRA,DIESEL S500,R$ / litro,6.89,2026-10-23
515,36411940000200,VESCOVI & BITTI LTDA,POSTO TREVAO,AVENIDA FLORESTAL,838,NaN,SEGATTO,29192154,ARACRUZ,ESPIRITO SANTO,VIBRA,DIESEL S10,R$ / litro,6.99,2026-10-23
516,36411940000200,VESCOVI & BITTI LTDA,POSTO TREVAO,AVENIDA FLORESTAL,838,NaN,SEGATTO,29192154,ARACRUZ,ESPIRITO SANTO,VIBRA,ETANOL,R$ / litro,5.09,2026-10-23
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20393,50022752000121,COMERCIAL DE GAS 7 LTDA,NaN,AVENIDA CARLOS LINDENBERG,1896,LOJA 02,ARIBIRI,29120568,VILA VELHA,ESPIRITO SANTO,BRANCA,GLP,R$ / 13 kg,100.00,2026-10-20
20406,3948877000369,AUTO POSTO SANTA ANA LTDA,NaN,RODOVIA DO CAFE,1871,NaN,CARLOS GERMANO NAUMANN,29705200,COLATINA,ESPIRITO SANTO,ULTRAGAZ,GLP,R$ / 13 kg,99.99,2026-10-22
20675,50202843000149,CAPIXABA COMERCIO DE GLP LTDA,NaN,RODOVIA SERAFIM DERENZI,10170,NaN,JOANA D´ARC,29048015,VITORIA,ESPIRITO SANTO,SUPERGASBRAS ENERGIA,GLP,R$ / 13 kg,100.00,2026-10-19
20713,47350901000258,EXPRESSO GAS E AGUA LTDA,NaN,RUA HENRIQUE DE ALMEIDA,13,NaN,CASTELO BRANCO,29709085,COLATINA,ESPIRITO SANTO,ULTRAGAZ,GLP,R$ / 13 kg,110.00,2026-10-22
20781,12615931000183,MAI-MAR COMERCIO E TRANSPORTES LTDA,NaN,RUA BENEDITO CORREIA PENHA,279,NaN,ARIBIRI,29120311,VILA VELHA,ESPIRITO SANTO,BRANCA,GLP,R$ / 13 kg,115.00,2026-10-21